import Link from "next/link";

export default function LegalPage() {
  return (
    <main className="legal-page">
      <header className="legal-header">
        <div className="legal-intro">
          <p className="eyebrow">Legal</p>
          <h1>Terms & policies</h1>
          <p className="lede">
            These terms describe how this showcase can be used, what you can
            expect from the AI responses, and how third-party software and
            services are involved.
          </p>
        </div>
        <div className="legal-actions">
          <Link className="ghost-button" href="/">
            Back to showcase
          </Link>
        </div>
      </header>

      <div className="panel legal-card">
        <section className="legal-section">
          <h2>Terms of service</h2>
          <p>
            By accessing or using this showcase, you agree to these terms. If
            you do not agree, please do not use the site.
          </p>
          <ul className="legal-list">
            <li>Use the site for evaluation and discussion of projects.</li>
            <li>Do not attempt to disrupt, scrape, or abuse the service.</li>
            <li>The showcase owner may update or remove content at any time.</li>
          </ul>
        </section>

        <section className="legal-section">
          <h2>AI assistance and accuracy</h2>
          <p>
            Chat responses are generated by AI and can be inaccurate or
            incomplete. Verify important details against the linked
            repositories and source material.
          </p>
        </section>

        <section className="legal-section">
          <h2>Content and intellectual property</h2>
          <p>
            Project content, trademarks, and logos belong to their respective
            owners. You may view and discuss the content for evaluation, but do
            not reuse it without permission.
          </p>
        </section>

        <section className="legal-section">
          <h2>Data and privacy</h2>
          <p>
            Chat prompts and usage data may be stored to operate the service,
            enforce limits, and improve quality. Do not include sensitive or
            confidential information.
          </p>
        </section>

        <section className="legal-section">
          <h2>Third-party services</h2>
          <p>
            This site integrates third-party services such as GitHub, OpenAI,
            and Stripe. Your use of those services is subject to their own
            terms and privacy policies.
          </p>
        </section>

        <section className="legal-section">
          <h2>Open source software</h2>
          <p>
            This site uses open source software. Third-party licenses apply and
            are available in the project repository.
          </p>
        </section>

        <section className="legal-section">
          <h2>Disclaimer</h2>
          <p>
            The site is provided &quot;as is&quot; without warranties of any
            kind. The showcase owner is not liable for damages or losses
            resulting from use of the site or reliance on its content.
          </p>
        </section>
      </div>
    </main>
  );
}
